stages:
  download_feeds:
    cmd: python exp/download_feeds.py
    deps:
      - exp/download_feeds.py
    outs:
      - data/documents.jsonl
    metrics:
      - data/download_feeds.json
  index_documents:
    cmd: python exp/index_documents.py
    deps:
      - exp/index_documents.py
      - data/documents.jsonl
    params:
      - index_documents
    outs:
      - data/document_store.json
    metrics:
      - data/index_documents.json
  model_topics:
    cmd: python exp/model_topics.py
    deps:
      - exp/model_topics.py
      - data/document_store.json
    params:
      - model_topics
    metrics:
      - data/model_topics.json
