model_topics:
  days: 1
  reps: 31
  topic_merge_delta: 0.1
  umap:
    n_neighbors: 50
    min_dist: 0.1
    n_components: 5
    metric: euclidean
  hdbscan:
    min_cluster_size: 15
    min_samples: null
    cluster_selection_epsilon: 0.0
    alpha: 1.0
